### ISSUE TITLE
3D touch

### ISSUE THREAD

**Issue by tellfa** [michelelacorte/ForceTouch#1]
Are this library is 3D Touch ?

**Comment by michelelacorte** [comment]
Yes sir, you can implement 3D Touch with your custom level of screen pressure

**Comment by tellfa** [comment]
@michelelacorte , thank you my bro 👍 
Can you write simple code for show image in your library? for example sort images with grid layout, when click on this images and use forceTouch show this image in dialog. such as instagram.

with this simple understand your codes for all users. ❤️

**Comment by michelelacorte** [comment]
Please open question on [StackOverflow](http://stackoverflow.com/) for this.
