### ISSUE TITLE
All touches register with the same pressure on Galaxy S7 Edge

### ISSUE THREAD

**Issue by jacobminer** [michelelacorte/ForceTouch#2]
If the library requires a special screen, you should probably mention that in the README.

**Comment by michelelacorte** [comment]
The MotionEvent class was introduced on API 1, so this not required "special screen", however library records and then sends a small vibration to the "force" touch of the finger, it is not progressive, of course I have not been able to test on too many devices, so I would be happy if you tell me something extra about this.

**Comment by jacobminer** [comment]
So, is the point of the library to vibrate when the user touches the screen? I was under the impression that it was supposed to simulate the iOS 3D touch feature.

**Comment by jacobminer** [comment]
Nevermind, I understand now.

**Comment by michelelacorte** [comment]
Exactly, well, it vibrates to give the impression of depth of the screen, then using the Library you can implement any method you want to execute when the level of the screen is above a designated threshold

This might help some other.
